# Generated by Django 2.0.3 on 2018-03-31 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image_filename', models.CharField(max_length=500)),
                ('image_caption', models.CharField(max_length=500)),
                ('formula', models.CharField(blank=True, max_length=500)),
                ('strunz', models.CharField(blank=True, max_length=500)),
                ('crystal_system', models.CharField(max_length=500)),
                ('unit_cell', models.CharField(blank=True, max_length=500)),
                ('color', models.CharField(blank=True, max_length=500)),
                ('crystal_symmetry', models.CharField(blank=True, max_length=500)),
                ('cleavage', models.CharField(blank=True, max_length=500)),
                ('mohs_scale', models.CharField(blank=True, max_length=500)),
                ('luster', models.CharField(blank=True, max_length=500)),
                ('streak', models.CharField(blank=True, max_length=500)),
                ('diaphaneity', models.CharField(blank=True, max_length=500)),
                ('optical_prop', models.CharField(blank=True, max_length=500)),
                ('refractive_index', models.CharField(blank=True, max_length=500)),
                ('crystal_habit', models.CharField(blank=True, max_length=500)),
                ('specific_gravity', models.CharField(blank=True, max_length=500)),
                ('categories', models.ManyToManyField(to='mineral_detail.Category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineral_detail.Group')),
            ],
        ),
    ]
